### ISSUE TITLE
checkbox value not saving?

### ISSUE THREAD

**Issue by nicollasricas** [elgatosf/streamdeck-pisamples#1]
![image](https://user-images.githubusercontent.com/7860985/62909258-dbd5e080-bd49-11e9-89c0-f910b592e02c.png)

**I tried to reinstall the PI samples plugin and delete every key same results.**

**Comment by Timac** [comment]
The PISamples plugin is a demo plugin to demonstrate the various UI elements available in the Property Inspector. The various settings are not saved /restored. If you want to save/restore the settings, you should call the `SetSettings()` API. The documentation is available here: https://developer.elgato.com/documentation/stream-deck/sdk/events-sent/#setsettings
