### ISSUE TITLE
Accessibility

### ISSUE THREAD

**Issue by dotherightthing** [elgatosf/streamdeck-pisamples#11]
Accessibility doesn't seem to be uniformly applied in the HTML samples.

For example, labels are required to identify elements to users who rely on Assistive Technology to navigate forms.

While [some elements do have an accompanying `label`](https://github.com/elgatosf/streamdeck-pisamples/blob/fbd904e0584d3f2b1eb949f305373072d2fc69c7/Sources/com.elgato.pisamples.sdPlugin/index_pi.html#L98C25-L98C25), [others just `div.sdpi-item-label`](https://github.com/elgatosf/streamdeck-pisamples/blob/fbd904e0584d3f2b1eb949f305373072d2fc69c7/Sources/com.elgato.pisamples.sdPlugin/index_pi.html#L143).

Of course this is part of a bigger question about how you handle Accessibility for the Stream Deck window and everything else in it.

**Comment by tiptronic** [comment]
Thanks for the note @dotherightthing,
You are right and we are aware of some inconsitencies and will update the samples asap.
