### ISSUE TITLE
Dynamic content

### ISSUE THREAD

**Issue by NijsJonas** [elgatosf/streamdeck-pisamples#2]
Hi all,
i am creating a streamdeck plugin in javascript with two buttons, one to login to our api and one to send specific commands to it.
The login button works fine, i can login and retreive a token from our api.
Now once logged in i need to change the options in the select list of button 2 to all the options that are retreived from the api.

How can i dynamicly add and remove options from a list in a buttons property inspector ?

**Comment by elgatosystems** [comment]
A similar discussion is here: https://github.com/elgatosf/streamdeck-plugintemplate/issues/5
