### ISSUE TITLE
Sample Selectors Clear on Button Reselect

### ISSUE THREAD

**Issue by Soaryn** [elgatosf/streamdeck-pisamples#7]
The sample for the dropdown list is a little lacking as it doesn't demonstrate how to actually keep the value on the button.

![image](https://user-images.githubusercontent.com/1859805/167288112-848d8a06-2248-40d3-88b0-e87b29f2bd5f.png)

No matter which is selected, when the button is deselected in StreamDeck, then reselected, the first value is always the current value.

**Comment by tiptronic** [comment]
I am not sure I understand what you mean by 'keeping the value on the button'..
If you mean saving the value to the settings an re-apply those settings when activating the property inspector, then yes - settings are not saved in PISamples, but you could just save the setting using `setSettings` and re-apply this setting when the property inspector is opened again (you'll find those settings in the `connected` event's payload...

**Comment by Soaryn** [comment]
I'll try to tinker with it, but it would be helpful to have a sample that does show this in action. I come from a C# environment, so I am having difficult with javascript and lack of intellisense on any of the code base that I am used to using in Rider.

**Comment by tiptronic** [comment]
Unfortunately I don't know what 'Rider' is, but saving settings is basically a 1-liner. (`$SD.setSettings(value, context);`)

If you search for `setSettings` here in our repositories you'll find plenty of samples how to use it:
e.g.:
https://github.com/elgatosf/streamdeck-plugin-template/blob/6b2f59c531b25538885806667289ee8eae992de3/src/com.elgato.template.sdPlugin/actions/template/property-inspector/inspector.js

More Info here:
https://developer.elgato.com/documentation/stream-deck/sdk/events-sent/#setsettings

**Comment by Soaryn** [comment]
That is a 404 github link
Rider is an IDE focused predominantly on C# but can do other languages, like JS as well. 

Whether or not it is a one liner or not (I am glad it is simple) still doesn't negate the fact a sample should likely have it on perhaps the more inclusive of the samples.  ;)

**Comment by tiptronic** [comment]
Sorry for the bad link.

The PISamples plugin just shows some best practices on how to layout UI-elements in the property inspector.
Other samples cover different kinds of topics in various languages. It's simply impossible to show every aspect of a plugin (especially if it comes to really simple API-calls ;))

Here's a beginner's template, which contains lots of comments, how things are supposed to work (in that template).

https://github.com/elgatosf/streamdeck-plugintemplate/blob/master/Sources/com.elgato.template.sdPlugin/propertyinspector/js/index_pi.js

I also took a note to add some more code-examples in upcoming new sample-plugins.

But you can also look into one of the other plugins here - most of the plugins are fully working plugins (also found on the StreamDeck store) and show all kind of techniques how to handle things.
