### ISSUE TITLE
Tabs clickTab() contains invalid line

### ISSUE THREAD

**Issue by theca11** [elgatosf/streamdeck-pisamples#8]
The `clickTab()` function (which is the same as the one in the docs) contains this line: `activeTab = clickedTab.dataset?.target;`, but `activeTab` is not defined nor used anywhere in the rest of the code. I guess this comes from a previous version of the function, but it should be removed

https://github.com/elgatosf/streamdeck-pisamples/blob/2e2d0d4bfb5893625c5704734cf920fae5d20d8b/Sources/com.elgato.pisamples.sdPlugin/js/index_pi.js#L115-L128

**Comment by tiptronic** [comment]
@theca11 thx for the report
This (and more) should be fixed and improved in the latest version (2.0.3)

**Comment by theca11** [comment]
Notice that this is also present in the documentation and in the javascript plugin template repo, in case you want to update them at some point

**Comment by tiptronic** [comment]
thx! 
This is fixed in the docs and will update soon...
